before:
  hooks:
  - go mod tidy
    # As part of the release doc files are included as a separate deliverable for
    # consumption by Packer.io. To include a separate docs.zip uncomment the following command.
    #- make ci-release-docs
builds:
- env:
  - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
  - -trimpath #removes all file system paths from the compiled executable
  ldflags:
  - '-s -w -X {{ .ModulePath }}/version.Version={{.Version}}'
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - '386'
  - arm64
  ignore:
  - goos: darwin
    goarch: '386'
  - goos: linux
    goarch: '386'
  - goos: windows
    goarch: arm64
  binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
archives:
- format: zip
  files:
  - none*
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
- artifacts: checksum
  args:
  # if you are using this is in a GitHub action or some other automated pipeline, you
  # need to pass the batch flag to indicate its not interactive.
  - "--batch"
  - "--local-user"
  - "{{ .Env.GPG_FINGERPRINT }}"
  - "--output"
  - "${signature}"
  - "--detach-sign"
  - "${artifact}"
release:
  # As part of the release doc files are included as a separate deliverable for consumption by Packer.io.
  # To include a separate docs.zip uncomment the extra_files config and the docs.zip command hook above.
  #extra_files:
  #- glob: ./docs.zip
changelog:
  skip: true
