---
version: 2.1

jobs:
  test:
    working_directory: /tmp/project
    docker:
    - image: matthewschuchard/packer-plugin
    resource_class: small
    steps:
    - checkout
    - run:
        name: install prereqs
        command: apk add --no-cache --update build-base && touch /usr/local/bin/py.test
    - run:
        name: build
        command: make build
    - run:
        name: unit test
        command: make unit

workflows:
  execute_tests:
    jobs:
    - test
