---
version: 2.1

jobs:
  test:
    working_directory: /tmp/project
    docker:
    - image: matthewschuchard/packer-plugin
    resource_class: small
    steps:
    - checkout
    - run:
        name: install prereqs and setup fake pytest
        command: apk add --no-cache --update make && cp fixtures/py.test /usr/local/bin/py.test
    - run:
        name: build
        command: make build
    - run:
        name: unit test with fake py.test
        command: PATH="${PATH}:/usr/local/bin" make unit

workflows:
  execute_tests:
    jobs:
    - test
