---
name: build and test

on:
  push:
    branches: [master]
    paths:
    - '**.go'
    - 'go.mod'
  pull_request:
    branches: [master]
    paths:
    - '**.go'
    - 'go.mod'

jobs:
  go-build:
    runs-on: ubuntu-22.04
    container: golang:1.18-alpine
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install prereqs
      run: apk add --no-cache --update build-base && touch /usr/local/bin/py.test
    - name: build
      run: make build
    - name: unit test
      run: make unit
