---
name: release
on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    name: create and publish packer-plugin-testinfra release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        # Allow goreleaser to access older tag information.
        fetch-depth: 0
    - name: set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: describe plugin
      id: plugin_describe
      run: echo "api_version=$(go run . describe | jq -r '.api_version')" >> "$GITHUB_OUTPUT"
    - name: import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
    - name: run GoReleaser
      uses: goreleaser/goreleaser-action@v7
      with:
        version: '~> v2'
        args: release --clean
      env:
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        API_VERSION: ${{ steps.plugin_describe.outputs.api_version }}
